//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class ActionCaissier : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fCaissier;
        [Size(50)]
        public string Caissier
        {
            get { return fCaissier; }
            set { SetPropertyValue<string>("Caissier", ref fCaissier, value); }
        }
        string fTypeAction;
        public string TypeAction
        {
            get { return fTypeAction; }
            set { SetPropertyValue<string>("TypeAction", ref fTypeAction, value); }
        }
        DateTime fDateHeure;
        public DateTime DateHeure
        {
            get { return fDateHeure; }
            set { SetPropertyValue<DateTime>("DateHeure", ref fDateHeure, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
    }

}
