//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class Article : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fLibArticle;
        [Size(500)]
        public string LibArticle
        {
            get { return fLibArticle; }
            set { SetPropertyValue<string>("LibArticle", ref fLibArticle, value); }
        }
        string fCodeArticle;
        [Size(500)]
        public string CodeArticle
        {
            get { return fCodeArticle; }
            set { SetPropertyValue<string>("CodeArticle", ref fCodeArticle, value); }
        }
        decimal fPrixUnitaire;
        public decimal PrixUnitaire
        {
            get { return fPrixUnitaire; }
            set { SetPropertyValue<decimal>("PrixUnitaire", ref fPrixUnitaire, value); }
        }
        string fUnite;
        [Size(50)]
        public string Unite
        {
            get { return fUnite; }
            set { SetPropertyValue<string>("Unite", ref fUnite, value); }
        }
        DateTime fDateCreation;
        public DateTime DateCreation
        {
            get { return fDateCreation; }
            set { SetPropertyValue<DateTime>("DateCreation", ref fDateCreation, value); }
        }
        [Association(@"TransactionArticleReferencesArticle")]
        public XPCollection<TransactionArticle> TransactionArticles { get { return GetCollection<TransactionArticle>("TransactionArticles"); } }
    }

}
