//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class Caissier : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fNom;
        [Size(500)]
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
        string fPrenom;
        [Size(500)]
        public string Prenom
        {
            get { return fPrenom; }
            set { SetPropertyValue<string>("Prenom", ref fPrenom, value); }
        }
        string fMatricule;
        [Size(500)]
        public string Matricule
        {
            get { return fMatricule; }
            set { SetPropertyValue<string>("Matricule", ref fMatricule, value); }
        }
        DateTime fDateCreation;
        public DateTime DateCreation
        {
            get { return fDateCreation; }
            set { SetPropertyValue<DateTime>("DateCreation", ref fDateCreation, value); }
        }
        UserProfile fUserProfile;
        [Association(@"CaissierReferencesUserProfile")]
        public UserProfile UserProfile
        {
            get { return fUserProfile; }
            set { SetPropertyValue<UserProfile>("UserProfile", ref fUserProfile, value); }
        }
        [Association(@"TransactionReferencesCaissier")]
        public XPCollection<Transaction> Transactions { get { return GetCollection<Transaction>("Transactions"); } }
    }

}
