//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class PointDeVente : XPLiteObject
    {
        Guid fID;
        [Key(true)]
        public Guid ID
        {
            get { return fID; }
            set { SetPropertyValue<Guid>("ID", ref fID, value); }
        }
        string fRaisonSociale;
        [Size(500)]
        public string RaisonSociale
        {
            get { return fRaisonSociale; }
            set { SetPropertyValue<string>("RaisonSociale", ref fRaisonSociale, value); }
        }
        string fAdresse;
        [Size(500)]
        public string Adresse
        {
            get { return fAdresse; }
            set { SetPropertyValue<string>("Adresse", ref fAdresse, value); }
        }
        string fTel;
        [Size(500)]
        public string Tel
        {
            get { return fTel; }
            set { SetPropertyValue<string>("Tel", ref fTel, value); }
        }
    }

}
