//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class Transaction : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        Guid fUniqueID;
        public Guid UniqueID
        {
            get { return fUniqueID; }
            set { SetPropertyValue<Guid>("UniqueID", ref fUniqueID, value); }
        }
        string fClient;
        [Size(500)]
        public string Client
        {
            get { return fClient; }
            set { SetPropertyValue<string>("Client", ref fClient, value); }
        }
        DateTime fDateTransaction;
        public DateTime DateTransaction
        {
            get { return fDateTransaction; }
            set { SetPropertyValue<DateTime>("DateTransaction", ref fDateTransaction, value); }
        }
        decimal fMontantTotal;
        public decimal MontantTotal
        {
            get { return fMontantTotal; }
            set { SetPropertyValue<decimal>("MontantTotal", ref fMontantTotal, value); }
        }
        Caissier fCaissier;
        [Association(@"TransactionReferencesCaissier")]
        public Caissier Caissier
        {
            get { return fCaissier; }
            set { SetPropertyValue<Caissier>("Caissier", ref fCaissier, value); }
        }
        TypePaiement fTypePaiement;
        [Association(@"TransactionReferencesTypePaiement")]
        public TypePaiement TypePaiement
        {
            get { return fTypePaiement; }
            set { SetPropertyValue<TypePaiement>("TypePaiement", ref fTypePaiement, value); }
        }
        string fFlag;
        [Size(500)]
        public string Flag
        {
            get { return fFlag; }
            set { SetPropertyValue<string>("Flag", ref fFlag, value); }
        }
        [Association(@"TransactionArticleReferencesTransaction")]
        public XPCollection<TransactionArticle> TransactionArticles { get { return GetCollection<TransactionArticle>("TransactionArticles"); } }
    }

}
