//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class UserProfile : XPLiteObject
    {
        int fUserId;
        [Key(true)]
        public int UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<int>("UserId", ref fUserId, value); }
        }
        string fUserName;
        [Indexed(Name = @"UQ__UserProf__C9F2845647190936", Unique = true)]
        [Size(56)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>("UserName", ref fUserName, value); }
        }
        [Association(@"CaissierReferencesUserProfile")]
        public XPCollection<Caissier> Caissiers { get { return GetCollection<Caissier>("Caissiers"); } }
    }

}
