//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class webpages_Membership : XPLiteObject
    {
        int fUserId;
        [Key]
        public int UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<int>("UserId", ref fUserId, value); }
        }
        DateTime fCreateDate;
        public DateTime CreateDate
        {
            get { return fCreateDate; }
            set { SetPropertyValue<DateTime>("CreateDate", ref fCreateDate, value); }
        }
        string fConfirmationToken;
        [Size(128)]
        public string ConfirmationToken
        {
            get { return fConfirmationToken; }
            set { SetPropertyValue<string>("ConfirmationToken", ref fConfirmationToken, value); }
        }
        bool fIsConfirmed;
        public bool IsConfirmed
        {
            get { return fIsConfirmed; }
            set { SetPropertyValue<bool>("IsConfirmed", ref fIsConfirmed, value); }
        }
        DateTime fLastPasswordFailureDate;
        public DateTime LastPasswordFailureDate
        {
            get { return fLastPasswordFailureDate; }
            set { SetPropertyValue<DateTime>("LastPasswordFailureDate", ref fLastPasswordFailureDate, value); }
        }
        int fPasswordFailuresSinceLastSuccess;
        public int PasswordFailuresSinceLastSuccess
        {
            get { return fPasswordFailuresSinceLastSuccess; }
            set { SetPropertyValue<int>("PasswordFailuresSinceLastSuccess", ref fPasswordFailuresSinceLastSuccess, value); }
        }
        string fPassword;
        [Size(128)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>("Password", ref fPassword, value); }
        }
        DateTime fPasswordChangedDate;
        public DateTime PasswordChangedDate
        {
            get { return fPasswordChangedDate; }
            set { SetPropertyValue<DateTime>("PasswordChangedDate", ref fPasswordChangedDate, value); }
        }
        string fPasswordSalt;
        [Size(128)]
        public string PasswordSalt
        {
            get { return fPasswordSalt; }
            set { SetPropertyValue<string>("PasswordSalt", ref fPasswordSalt, value); }
        }
        string fPasswordVerificationToken;
        [Size(128)]
        public string PasswordVerificationToken
        {
            get { return fPasswordVerificationToken; }
            set { SetPropertyValue<string>("PasswordVerificationToken", ref fPasswordVerificationToken, value); }
        }
        DateTime fPasswordVerificationTokenExpirationDate;
        public DateTime PasswordVerificationTokenExpirationDate
        {
            get { return fPasswordVerificationTokenExpirationDate; }
            set { SetPropertyValue<DateTime>("PasswordVerificationTokenExpirationDate", ref fPasswordVerificationTokenExpirationDate, value); }
        }
    }

}
