//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NV_SYSTEM.Models.NV_SYSTEM_CAISSE
{

    public partial class webpages_Roles : XPLiteObject
    {
        int fRoleId;
        [Key(true)]
        public int RoleId
        {
            get { return fRoleId; }
            set { SetPropertyValue<int>("RoleId", ref fRoleId, value); }
        }
        string fRoleName;
        [Indexed(Name = @"UQ__webpages__8A2B6160EB3D5EAA", Unique = true)]
        [Size(256)]
        public string RoleName
        {
            get { return fRoleName; }
            set { SetPropertyValue<string>("RoleName", ref fRoleName, value); }
        }
    }

}
